name: Deploy to OCI (Oracle Cloud Infrastructure)
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.OCI_KEYFILE }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo "${{ secrets.OCI_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Build images and start up containers using docker-compose over SSH
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.OCI_USERNAME }}@${{ secrets.OCI_HOST }} -t "cd git/todo; git switch main; git pull; docker compose -f docker-compose-prod.yml build; docker compose -f docker-compose-prod.yml down; nohup docker compose -f docker-compose-prod.yml up -d"
